version: "3.8"
services:
  app:
    image: client
    restart: unless-stopped
    container_name: app
    hostname: furniture_app
    build:
      context: client
      target: runner
      dockerfile: Dockerfile
    
    environment:
      SERVERSIDE_API_URL: http://furniture_api:9000/graphql
      CLIENTSIDE_API_URL: http://localhost:9000/graphql
      JWT_SECRET: tynxcodejs
      NEXTAUTH_URL: http://localhost:3000
    
    ports: 
      - 3000:3000
    
    networks:
      - shared-network
  
  api:
    image: server
    restart: unless-stopped
    container_name: api
    hostname: furniture_api
    build:
      context: server
      target: production
      dockerfile: Dockerfile
    
    ports:
      - 9000:9000
    
    networks:
      - shared-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: /bin/sh -c "nginx -g 'daemon off;'"

    depends_on:
      api:
        condition: service_started
      app:
        condition: service_started
    
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge